# Generated by Django 3.1.1 on 2020-09-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Data unique identifier', max_length=120)),
                ('individual_name', models.CharField(help_text='Individual Name', max_length=120)),
                ('staff_name', models.CharField(help_text='Staff Name', max_length=120)),
                ('date', models.DateTimeField(help_text='Date')),
                ('shift', models.CharField(choices=[('A', 'AM'), ('P', 'PM')], help_text='Shift', max_length=2)),
                ('diet', models.CharField(help_text='Diet', max_length=200)),
                ('food_texture_choice', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], help_text='Yes/No', max_length=2)),
                ('food_texture_description', models.TextField(help_text='Did the individual tolerate food Texture')),
                ('food_texture1', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], help_text='B', max_length=2)),
                ('food_texture2', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], help_text='L', max_length=2)),
                ('food_texture3', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], help_text='D', max_length=2)),
                ('quantity_consumed1', models.CharField(choices=[('25', '25% or less'), ('50', '50% or less'), ('75', '75% or less'), ('100', '100% or less')], help_text='25% or less', max_length=3)),
                ('quantity_consumed2', models.CharField(choices=[('25', '25% or less'), ('50', '50% or less'), ('75', '75% or less'), ('100', '100% or less')], help_text='50% or less', max_length=3)),
                ('quantity_consumed3', models.CharField(choices=[('25', '25% or less'), ('50', '50% or less'), ('75', '75% or less'), ('100', '100% or less')], help_text='75% or less', max_length=3)),
                ('consumed_explain', models.CharField(blank=True, help_text='If Consumed less than 75% Please Explain', max_length=300)),
                ('liked_unliked', models.CharField(blank=True, help_text='What part of the meal did they like or did not like, if\n        applicable?', max_length=300)),
                ('incident_on_shift', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], help_text='Has there been an incident involving this individual\n        during your shift?', max_length=2)),
                ('incident_on_shift_explain', models.CharField(blank=True, help_text='Explain', max_length=300)),
                ('incident_report', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], help_text='If yes, has there been an incident report completed\n        before the end of your shift?', max_length=2)),
                ('incident_report_explain', models.CharField(blank=True, help_text='Explain', max_length=300)),
                ('incident_behavior', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], help_text='Did the individual display any behaviors during your\n        shift not identified in the BSP?', max_length=2)),
                ('incident_behavior_explain', models.CharField(blank=True, help_text='Explain', max_length=300)),
                ('observed_symptoms', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], help_text='Do you observe any sign and symptoms of illness involving\n        this individual during your shift?', max_length=2)),
                ('observed_symptoms_explain', models.CharField(blank=True, help_text='Explain', max_length=300)),
                ('medical_appointment', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], help_text='Is there a medical appointment scheduled and completed\n        during your shift?', max_length=2)),
                ('medical_appointment_explain', models.CharField(blank=True, help_text='Explain', max_length=300)),
                ('home_or_job', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], help_text='Is the individual home from the day program or from their\n        job?', max_length=2)),
                ('home_or_job_explain', models.CharField(blank=True, help_text='Explain', max_length=300)),
                ('side_effects', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], help_text='Are there any observable signs/symptoms of side effects\n        of medication(s)?', max_length=2)),
                ('side_effects_explain', models.CharField(blank=True, help_text='Explain', max_length=300)),
                ('adaptive_equipment', models.CharField(help_text='List the adaptive equipment:', max_length=300)),
                ('equipment_concern', models.CharField(blank=True, help_text='Any concerns with equipment, if so explain:', max_length=300)),
                ('program_implemented', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], help_text='Is all programs implemented as outlined?', max_length=2)),
                ('program_documented', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], help_text='Is Program Documentation completed as outlined?', max_length=2)),
                ('finance_discussion', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], help_text='Discussion of Finance?', max_length=2)),
                ('finance_discussion_explain', models.CharField(blank=True, help_text='Explain', max_length=300)),
                ('home_visitor', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], help_text='Is there a visitor in the home during your shift?', max_length=2)),
                ('summary1_date', models.DateTimeField(help_text='Date/Time')),
                ('summary1_initial', models.CharField(help_text='Staff Initial', max_length=120)),
                ('summary1', models.TextField(help_text='First Summary')),
                ('summary2_date', models.DateTimeField(help_text='Date/Time')),
                ('summary2_initial', models.CharField(help_text='Staff Initial', max_length=120)),
                ('summary2', models.TextField(help_text='Second Summary')),
                ('summary3_date', models.DateTimeField(help_text='Date/Time')),
                ('summary3_initial', models.CharField(help_text='Staff Initial', max_length=120)),
                ('summary3', models.TextField(help_text='Third Summary')),
                ('summary4_date', models.DateTimeField(blank=True, help_text='Date/Time', null=True)),
                ('summary4_initial', models.CharField(blank=True, help_text='Staff Initial', max_length=120)),
                ('summary4', models.TextField(blank=True, help_text='Fourth Summary')),
                ('residential_manager_review', models.CharField(help_text='Residential Manager Review', max_length=300)),
            ],
        ),
    ]
